spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booktracker
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog/001-init.sql
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true